version: '3'

services:
  pcparts-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pcparts
      - MYSQL_USER=pcparts
      - MYSQL_PASSWORD=admin
    volumes:
      - pcparts-mysql-volume:/var/lib/mysql
    ports:
      - "3306:3306"

  pcparts-backend:
    build: .
    env_file: .env
    environment:
      - BACKEND_PORT
      - DATABASE_HOST
      - DATABASE_PORT
      - DATABASE_NAME
      - DATABASE_USER
      - DATABASE_PASSWORD
    depends_on:
      - pcparts-mysql
    volumes:
      - ./data:/data
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"

volumes:
  pcparts-mysql-volume:
