name: 'Deploy'
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: 'Deploy to digital ocean app'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: maven
      - name: 'Switch to backend'
        run: cd backend
      - name: 'Get branch name'
        shell: bash
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: 'Build docker image'
        run: docker build -t pcparts-api:$BRANCH_NAME .
      - name: 'Install doctl'
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: 'Authenticate with registry'
        run: doctl registry login
      - name: 'Tag image for upload'
        run:
          docker tag bouncer-api:$BRANCH_NAME registry.digitalocean.com/jely2002/pcparts-api:$BRANCH_NAME
      - name: 'Deploy image to registry'
        run: docker push registry.digitalocean.com/jely2002/pcparts-api:$BRANCH_NAME
      - name: 'Create new app deployment'
        env:
          DIGITALOCEAN_APP_ID: ${{ secrets.DIGITALOCEAN_APP_ID }}
        run: doctl apps create-deployment $DIGITALOCEAN_APP_ID --force-rebuild

